import type { Lesson } from "@/types/learning";
import { frontendEngineeringLessons } from "@/content/frontend-engineering";

export {
  whatIsWebsiteAndWebPageLesson,
  howWebPageLoadsLesson,
  whatAreHtmlCssJavascriptLesson,
  htmlCssJsRolesLesson,
  indexCssJsFilesLesson,
  smallFrontendProjectStructureLesson,
  webFoundationsAssessmentLesson,
  htmlBasicStructureLesson,
  tagElementAttributeLesson,
  headingsParagraphsLinksImagesLesson,
  relativePathsBasicLesson,
  htmlBasicsAssessmentLesson,
  semanticHtmlStructureLesson,
  htmlSemanticBasicsLesson,
  semanticHtmlAssessmentLesson,
  linkVsButtonLesson,
  formLabelInputLesson,
  textareaSelectRequiredFieldsLesson,
  altTextBasicLesson,
  keyboardNavigationBasicLesson,
  basicAccessibilityChecklistLesson,
  formsBasicAccessibilityAssessmentLesson,
  whatIsCssLesson,
  cssSelectorDeclarationBasicLesson,
  cascadeSpecificityBasicLesson,
  cssBoxModelBasicLesson,
  cssPaddingMarginBasicLesson,
  cssBorderWidthBasicLesson,
  boxModelSpacingAssessmentLesson,
  cssCoreMechanicsAssessmentLesson,
  setupLocalProjectFolderLesson,
  openProjectInCodeEditorLesson,
  runHtmlInBrowserLesson,
  basicDevtoolsStaticPageLesson,
  saveProjectWithGitGithubLesson,
  localStaticWebsiteProjectAssessmentLesson,
  cssFlexboxBasicLesson,
  buildNavbarWithFlexboxLesson,
  cssGridBasicLesson,
  flexboxVsGridDecisionLesson,
  flexboxGridLayoutAssessmentLesson,
  mobileFirstCssLesson,
  cssBreakpointsBasicLesson,
  fluidSpacingTypographyBasicLesson,
  cssVariablesDarkModeBasicLesson,
  responsiveVisualSystemAssessmentLesson,
  whatIsJavascriptInBrowserLesson,
  javascriptValuesVariablesLesson,
  javascriptBasicFunctionsLesson,
  javascriptConditionalsLoopsBasicLesson,
  javascriptValuesTypesFunctionsAssessmentLesson,
  javascriptArrayDataUiLesson,
  javascriptObjectSingleItemLesson,
  javascriptArrayOfObjectsLesson,
  javascriptMapFilterDataTransformLesson,
  javascriptArraysObjectsDataModelingAssessmentLesson,
  javascriptDomSelectionBasicLesson,
  javascriptClickInputEventsLesson,
  javascriptFormSubmitBasicLesson,
  javascriptLocalStorageBasicLesson,
  javascriptFetchJsonBasicLesson,
  javascriptDomEventsFormsStorageFetchAssessmentLesson,
  setupLocalVanillaJsProjectLesson,
  connectLocalHtmlCssJsFilesLesson,
  buildFirstLocalJsInteractionLesson,
  saveLocalDataWithLocalstorageLesson,
  readDocsWhileDebuggingLocalJsLesson,
  localVanillaJavascriptAppAssessmentLesson,
  javascriptScopeBasicLesson,
  javascriptClosureUiExampleLesson,
  javascriptEsModulesImportExportLesson,
  javascriptSplitFilesLesson,
  javascriptScopeClosureModulesAssessmentLesson,
  javascriptPromiseBasicLesson,
  javascriptAsyncAwaitBasicLesson,
  javascriptTryCatchBasicLesson,
  javascriptAsyncUiStatesLesson,
  javascriptBasicRetryLesson,
  javascriptAsyncErrorHandlingAssessmentLesson,
  javascriptUrlTimerApiBasicLesson,
  javascriptClipboardStoragePatternsLesson,
  javascriptDataTransformationUiLesson,
  javascriptNetworkDebuggingLesson,
  javascriptBreakpointsConsoleStrategyLesson,
  javascriptBrowserApisDebuggingAssessmentLesson,
  whatAreNodejsAndNpmLesson,
  checkNodeAndNpmVersionLesson,
  packageJsonBasicLesson,
  npmInstallAndNpmRunLesson,
  dependencyVsDevDependencyBasicLesson,
  localToolingNpmBasicsAssessmentLesson,
  whatIsTypescriptLesson,
  typescriptPrimitiveTypesArraysLesson,
  typescriptObjectTypesLesson,
  typescriptFunctionTypesLesson,
  typescriptOptionalFieldsLesson,
  typescriptCoreTypesAssessmentLesson,
  typescriptUnionTypesLesson,
  typescriptNarrowingLesson,
  typescriptDiscriminatedUnionUiStateLesson,
  typescriptBasicGenericsLesson,
  typescriptBasicUtilityTypesLesson,
  typescriptPracticalTypeDesignAssessmentLesson,
  typescriptApiResponseTypesLesson,
  typescriptFormInputDataLesson,
  typescriptComponentReadyDataShapesLesson,
  typescriptReusableFrontendLogicLesson,
  typescriptReadableTypesLesson,
  typescriptTypedFrontendBoundariesAssessmentLesson,
  reactWhatIsComponentLesson,
  reactJsxBasicsLesson,
  reactPropsAndChildrenLesson,
  reactSplittingUiComponentsLesson,
  reactComponentModelAssessmentLesson,
  reactUseStateBasicsLesson,
  reactEventHandlingLesson,
  reactConditionalRenderingLesson,
  reactListsAndKeysLesson,
  reactDerivedDisplayLesson,
  reactStateEventsRenderingAssessmentLesson,
  reactControlledInputsLesson,
  reactFormSubmitLesson,
  reactCompositionPatternsLesson,
  reactLiftingStateWhenNeededLesson,
  reactFormsCompositionAssessmentLesson,
  setupLocalReactProjectLesson,
  runReactDevServerLesson,
  understandReactSrcStructureLesson,
  createFirstLocalReactComponentLesson,
  addReactStateAndEventLocallyLesson,
  saveReactProjectToGithubLesson,
  localReactAppAssessmentLesson,
  reactWhenUseEffectLesson,
  reactEffectCleanupDependenciesLesson,
  reactCustomHookBasicsLesson,
  reactBrowserSubscriptionHookLesson,
  reactCustomHooksEffectsAssessmentLesson,
  reactStateColocationLesson,
  reactDerivedStateLesson,
  reactReducerPatternLesson,
  reactContextWhenNeededLesson,
  reactStateStrategyAssessmentLesson,
  reactLoadingStateLesson,
  reactErrorStateLesson,
  reactEmptyStateLesson,
  reactRetryPatternLesson,
  reactReusableUiStatesAssessmentLesson,
  reactErrorBoundariesLesson,
  reactFallbackUiLesson,
  reactSuspenseBasicsLesson,
  reactRetryRecoveryPatternsLesson,
  reactResilienceSuspenseBasicsAssessmentLesson,
  reactRenderCostLesson,
  reactMeasuringBeforeOptimizingLesson,
  reactUseMemoUseCallbackWhenUsefulLesson,
  reactExpensiveListsLesson,
  reactPerformanceAwarenessAssessmentLesson,
  reactCompoundComponentsLesson,
  reactSlotsAndChildrenPatternsLesson,
  reactReusableFormFieldPatternLesson,
  reactAvoidingOverAbstractionLesson,
  reactAdvancedComponentPatternsAssessmentLesson,
  nextjsAppDirectoryLesson,
  nextjsPageAndLayoutFilesLesson,
  nextjsNestedRoutesLesson,
  nextjsDynamicRoutesLesson,
  nextjsRouteGroupsLesson,
  nextjsAppDirectoryRoutingAssessmentLesson,
  nextjsServerComponentsLesson,
  nextjsClientComponentsLesson,
  nextjsUseClientBoundaryLesson,
  nextjsPassingPropsAcrossBoundariesLesson,
  nextjsCommonBoundaryMistakesLesson,
  nextjsServerClientComponentsAssessmentLesson,
  nextjsLoadingUiLesson,
  nextjsErrorUiLesson,
  nextjsRouteHandlersLesson,
  nextjsMetadataLesson,
  nextjsEnvironmentVariablesLesson,
  nextjsRouteBehaviorAssessmentLesson,
  setupLocalNextjsProjectLesson,
  runNextjsDevServerLesson,
  createNextjsRouteLayoutLesson,
  addNextjsLoadingErrorUiLesson,
  addNextjsMetadataLesson,
  pushNextjsProjectToGithubLesson,
  localNextjsAppAssessmentLesson,
  nextjsLoginRegisterUxLesson,
  nextjsLogoutSessionAwareNavLesson,
  nextjsPublicProtectedRoutesLesson,
  nextjsAuthErrorStatesLesson,
  nextjsAuthenticationSessionAwareUiAssessmentLesson,
  nextjsSupabaseClientBoundariesLesson,
  nextjsRlsConceptLesson,
  nextjsServiceLayerLesson,
  nextjsPersistingUserDataLesson,
  nextjsProfileRowsLesson,
  nextjsSupabaseBackendIntegrationAssessmentLesson,
  nextjsVercelDeploymentLesson,
  nextjsProductionEnvironmentSetupLesson,
  nextjsProductionLogsLesson,
  nextjsCachingBasicsLesson,
  nextjsDeploymentDebuggingLesson,
  nextjsProductionOperationsAssessmentLesson,
  reactHookFormRegistrationLesson,
  zodFormSchemaLesson,
  reactHookFormFieldErrorsLesson,
  reactHookFormSubmitStateLesson,
  reactHookFormSchemaReuseLesson,
  reactHookFormZodAssessmentLesson,
  validationInlineErrorsLesson,
  validationSummaryErrorsLesson,
  validationFocusManagementLesson,
  validationDisabledStateLesson,
  validationSuccessStateLesson,
  validationUxAccessibleErrorsAssessmentLesson,
  serverStateVsClientStateLesson,
  serverStateLoadingErrorEmptyLesson,
  serverStateMappingApiResponsesLesson,
  serverStateOptimisticUiBasicsLesson,
  serverStateThinkingAssessmentLesson,
} from "@/content/frontend-engineering";

export const writingDailyUpdateLesson: Lesson = {
  id: "writing-daily-update",
  trackId: "english-for-tech-careers",
  moduleId: "english-for-remote-work",
  title: "Menulis Daily Update untuk Kerja Remote",
  slug: "writing-daily-update",
  description:
    "Latihan menulis daily update yang ringkas, jelas, dan relevan untuk tim kerja remote lintas fungsi.",
  contentLanguage: "bilingual",
  level: "beginner",
  estimatedMinutes: 20,
  objectives: [
    "Memahami struktur daily update yang efektif untuk konteks kerja remote",
    "Menulis update berbahasa Inggris dengan format yang mudah dibaca tim",
    "Menyampaikan progres, plan, dan blocker secara jelas",
  ],
  skillTags: ["Technical English", "Remote Communication", "Writing Practice"],
  blocks: [
    {
      id: "writing-daily-update-intro",
      type: "text",
      title: "Kenapa daily update itu penting?",
      content:
        "Di tim remote, daily update membuat semua orang tahu progres terbaru tanpa menunggu meeting panjang. Format yang ringkas membuat engineer, PM, dan designer bisa cepat memahami apa yang sudah selesai, rencana berikutnya, dan blocker yang perlu dibantu.",
    },
    {
      id: "writing-daily-update-practical-note",
      type: "callout",
      variant: "tip",
      title: "Pakai format sederhana yang konsisten",
      content:
        "Gunakan format: Yesterday / Today / Blockers. Hindari kalimat terlalu panjang. Fokus pada dampak pekerjaan dan hal yang butuh kolaborasi dari tim.",
    },
    {
      id: "writing-daily-update-writing-practice",
      type: "writing-practice",
      prompt:
        "Tulis daily update singkat dalam bahasa Inggris menggunakan konteks realistis pekerjaan remote.\n\nTemplate yang bisa kamu pakai:\n- Yesterday: ...\n- Today: ...\n- Blockers: ...",
      placeholder:
        "Contoh:\nYesterday: I finished ...\nToday: I will work on ...\nBlockers: I need ...",
      checklist: [
        "Menyebutkan progres yang spesifik, bukan terlalu umum",
        "Rencana hari ini jelas dan bisa ditindaklanjuti",
        "Blocker ditulis dengan kebutuhan bantuan yang konkret",
      ],
      modelAnswer:
        "Yesterday: I finished the responsive navbar implementation and updated the PR with accessibility fixes.\nToday: I will integrate the settings API and write unit tests for the form validation.\nBlockers: I need confirmation from backend about the final response shape for the settings endpoint.",
    },
    {
      id: "writing-daily-update-summary",
      type: "summary",
      points: [
        "Daily update yang baik harus ringkas, spesifik, dan mudah dipahami tim.",
        "Format Yesterday / Today / Blockers membuat komunikasi tetap terstruktur.",
        "Tulis blocker dengan jelas supaya tim tahu bantuan apa yang dibutuhkan.",
      ],
    },
  ],
  completionRule: {
    requiredBlockIds: [
      "writing-daily-update-intro",
      "writing-daily-update-practical-note",
      "writing-daily-update-writing-practice",
      "writing-daily-update-summary",
    ],
  },
};

export const lessons: Lesson[] = [
  ...frontendEngineeringLessons,
  writingDailyUpdateLesson,
];
